{"data": [{"Advisory": {"CVE": ["CVE-2018-8768"], "FixedIn": [{"ecosystem": "python", "identifier": "5.4.1", "name": "notebook", "namespace": "github:python", "range": "< 5.4.1"}], "Metadata": {"CVE": ["CVE-2018-8768"]}, "Severity": "Low", "Summary": "Low severity vulnerability that affects notebook", "ghsaId": "GHSA-6cwv-x26c-w2q4", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-6cwv-x26c-w2q4", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2017-5524"], "FixedIn": [{"ecosystem": "python", "identifier": "4.3.12", "name": "Plone", "namespace": "github:python", "range": ">= 4.0 < 4.3.12"}, {"ecosystem": "python", "identifier": "5.1b1", "name": "Plone", "namespace": "github:python", "range": ">= 5.1a1 < 5.1b1"}, {"ecosystem": "python", "identifier": "5.0.7", "name": "Plone", "namespace": "github:python", "range": ">= 5.0rc1 < 5.0.7"}], "Metadata": {"CVE": ["CVE-2017-5524"]}, "Severity": "Medium", "Summary": "Moderate severity vulnerability that affects Plone", "ghsaId": "GHSA-p5wr-vp8g-q5p4", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-p5wr-vp8g-q5p4", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2016-9190"], "FixedIn": [{"ecosystem": "python", "identifier": "3.3.2", "name": "Pillow", "namespace": "github:python", "range": "< 3.3.2"}], "Metadata": {"CVE": ["CVE-2016-9190"]}, "Severity": "Medium", "Summary": "Moderate severity vulnerability that affects Pillow", "ghsaId": "GHSA-w4vg-rf63-f3j3", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-w4vg-rf63-f3j3", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2018-5773"], "FixedIn": [{"ecosystem": "python", "identifier": "None", "name": "markdown2", "namespace": "github:python", "range": "< 2.3.6"}], "Metadata": {"CVE": ["CVE-2018-5773"]}, "Severity": "Medium", "Summary": "Moderate severity vulnerability that affects markdown2", "ghsaId": "GHSA-p6h9-gw49-rqm4", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-p6h9-gw49-rqm4", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2018-6594"], "FixedIn": [{"ecosystem": "python", "identifier": "None", "name": "pycrypto", "namespace": "github:python", "range": "<= 2.6.1"}], "Metadata": {"CVE": ["CVE-2018-6594"]}, "Severity": "Medium", "Summary": "Moderate severity vulnerability that affects pycrypto", "ghsaId": "GHSA-6528-wvf6-f6qg", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-6528-wvf6-f6qg", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2018-7750"], "FixedIn": [{"ecosystem": "python", "identifier": "2.2.3", "name": "paramiko", "namespace": "github:python", "range": ">= 2.2.0 < 2.2.3"}, {"ecosystem": "python", "identifier": "2.3.2", "name": "paramiko", "namespace": "github:python", "range": ">= 2.3.0 < 2.3.2"}, {"ecosystem": "python", "identifier": "2.4.1", "name": "paramiko", "namespace": "github:python", "range": "= 2.4.0"}, {"ecosystem": "python", "identifier": "1.18.5", "name": "paramiko", "namespace": "github:python", "range": ">= 1.18.0 < 1.18.5"}, {"ecosystem": "python", "identifier": "1.17.6", "name": "paramiko", "namespace": "github:python", "range": "< 1.17.6"}, {"ecosystem": "python", "identifier": "2.0.8", "name": "paramiko", "namespace": "github:python", "range": ">= 2.0.0 < 2.0.8"}, {"ecosystem": "python", "identifier": "2.1.5", "name": "paramiko", "namespace": "github:python", "range": ">= 2.1.0 < 2.1.5"}], "Metadata": {"CVE": ["CVE-2018-7750"]}, "Severity": "High", "Summary": "High severity vulnerability that affects paramiko", "ghsaId": "GHSA-232r-66cg-79px", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-232r-66cg-79px", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2018-8097"], "FixedIn": [{"ecosystem": "python", "identifier": "0.7.5", "name": "eve", "namespace": "github:python", "range": "< 0.7.5"}], "Metadata": {"CVE": ["CVE-2018-8097"]}, "Severity": "High", "Summary": "High severity vulnerability that affects eve", "ghsaId": "GHSA-8jxq-75rw-fhj9", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-8jxq-75rw-fhj9", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2018-1002150"], "FixedIn": [{"ecosystem": "python", "identifier": "1.12.1", "name": "koji", "namespace": "github:python", "range": "= 1.12"}, {"ecosystem": "python", "identifier": "1.13.1", "name": "koji", "namespace": "github:python", "range": "= 1.13"}, {"ecosystem": "python", "identifier": "1.14.1", "name": "koji", "namespace": "github:python", "range": "= 1.14"}, {"ecosystem": "python", "identifier": "1.15.1", "name": "koji", "namespace": "github:python", "range": "= 1.15"}], "Metadata": {"CVE": ["CVE-2018-1002150"]}, "Severity": "Medium", "Summary": "Moderate severity vulnerability that affects koji", "ghsaId": "GHSA-6mww-xvh7-fq4f", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-6mww-xvh7-fq4f", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2018-9856"], "FixedIn": [{"ecosystem": "python", "identifier": "1.3.2", "name": "Kotti", "namespace": "github:python", "range": "< 1.3.2"}, {"ecosystem": "python", "identifier": "2.0.0b2", "name": "Kotti", "namespace": "github:python", "range": ">= 2.0 < 2.0.0b2"}], "Metadata": {"CVE": ["CVE-2018-9856"]}, "Severity": "Medium", "Summary": "Moderate severity vulnerability that affects Kotti", "ghsaId": "GHSA-3hq4-f2v6-q338", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-3hq4-f2v6-q338", "withdrawn": null}, "Vulnerability": {}}, {"Advisory": {"CVE": ["CVE-2018-0023"], "FixedIn": [{"ecosystem": "python", "identifier": "1.3.0", "name": "jsnapy", "namespace": "github:python", "range": "< 1.3.0"}], "Metadata": {"CVE": ["CVE-2018-0023"]}, "Severity": "Low", "Summary": "Low severity vulnerability that affects jsnapy", "ghsaId": "GHSA-qc55-vm3j-74gp", "namespace": "github:python", "url": "https://github.com/advisories/GHSA-qc55-vm3j-74gp", "withdrawn": null}, "Vulnerability": {}}], "next_token": ""}